language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5

install:
  - pip install psycopg2
  - pip install Django==$DJANGO_VERSION

script: python setup.py test

before_script:
  - psql -c 'create database django_nopassword;' -U postgres